### PR TITLE
Upstream merge 220122

### PR DESCRIPTION
**Pull request by CPhantasm**
## What is changing?

Upstream merge from 01/22

### Changes

 * Modsuits
 * Swarmers gone
 * Miriad other minor changes

## Why these changes?

merge good, new content in bad content out

### CODE REVIEW

**Comment by cakexensen** [comment]
SQL migration for this merge:

    CREATE TABLE `telemetry_connections` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `ckey` VARCHAR(32) NOT NULL,
        `telemetry_ckey` VARCHAR(32) NOT NULL,
        `address` INT(10) UNSIGNED NOT NULL,
        `computer_id` VARCHAR(32) NOT NULL,
        `first_round_id` INT(11) UNSIGNED NULL,
        `latest_round_id` INT(11) UNSIGNED NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `unique_constraints` (`ckey` , `telemetry_ckey` , `address` , `computer_id`)
    );

**Comment by CPhantasm** [comment]
The console still gets spammed with pipenet errors when booting a map, but there's a PR that fixes the error suppression on tg so eventually that'll go away. Doesn't seem to be affecting anything in game, distro/waste seemed to be working fine, and I tested the SM on Lima and nothing went awry. Probably safe to merge here.

**Comment by CPhantasm** [comment]
Actually, got a new runtime after leaving the SM running for a while. Don't merge yet

**Comment by CPhantasm** [comment]
Applied the fix Cake suggested and the fixes Inari found. Thank guys!

**Comment by cakexensen** [comment]
looks good, pipenet issues are recurrent and will be easier to fix next time.

**Pull request merged**
